sonar.projectKey=cuba
sonar.projectName=cuba
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx,**/build/**,**/public/**,scripts/**,**/*.py
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx
sonar.host.url=http://localhost:9000
sonar.login=sqa_83d25a28d8291212520662ba9a4427d8eb3dfc0b
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*
sonar.javascript.node.maxspace=4096
